### ISSUE TITLE
Resize is not fired after display:none

### ISSUE THREAD

**Issue by maxiplay** [PX10/px10-element-resize-detector#3]

**Comment by maxiplay** [comment]
Before display:none  event resize is fired. Next I display:none, no event is fired but It's "normal" I think. But when I remove display:none after, the resize event does not work anymore.


Another thing : I don't understand what the code do exactly, could you comment it ?

**Comment by eeid26** [comment]
I tried it and yes the problem exist. You should use polymer iron-resizable-behavior element instead of this experimental element.
