### ISSUE TITLE
in my application, in certains elements, detector does not work

### ISSUE THREAD

**Issue by maxiplay** [PX10/px10-element-resize-detector#4]
When I debug (in chrome) I see that contentDocument is null and the attached method is used just one time whereas when it work the attached method is used twice.

I discover if I change the <object> element into <iframe> I don't the problem anymore. Why ? that is the question.

**Comment by eeid26** [comment]
I do not know why you are seeing that. It might be some other issue with the element is being hidden.
I am not supporting this element anymore. Polymer has iron-resizable-behavior

**Comment by maxiplay** [comment]
Ok thank you. 

I did'nt know this behavior.

Thank you
